#!/usr/bin/env bash
# Numerical parity of llama2.zero vs karpathy/llama2.c.
#
# Builds the Zero example, fetches + builds the C reference, runs both on the
# real stories15M checkpoint, and diffs the generated token streams. At
# temperature 0 (greedy argmax) the streams must be byte-identical; with
# temperature > 0 they must also match once the seed (12345) and sampler are
# aligned, because the xorshift* PRNG is reproduced bit-for-bit. Both sampler
# paths are checked: plain multinomial (`-p 0`) and top-p nucleus
# (`-p <0..1>`) each reproduce `llama2.c` token-for-token.
#
# Both sides expand raw-byte `<0xNN>` fallback tokens to the actual byte (e.g.
# `<0x0A>` -> a newline), so the generated byte streams are directly comparable.
#
# Both binaries must link the *same* musl libm, or token-for-token parity is
# impossible: the Zero exe statically links zig's bundled musl, whose
# expf/sinf/cosf/powf/sqrtf differ by ~1 ULP from any other libm build. So the C
# reference is compiled with that very toolchain (`zig cc`, same target triple) —
# NOT the container's Alpine gcc/musl, whose libm skew silently breaks parity
# (most visibly on the int8 path, whose tighter logit margins turned a sub-ULP
# expf gap into flipped sampled tokens; see
# .docs/llama2/quant-temp-parity-divergence.md). The amd64 Alpine container is
# now only used to *run* the linux-musl-x64 binaries (under qemu on non-x64
# hosts). Requires Docker + zig. Override the data/cache dir with LLAMA2_DATA.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
data="${LLAMA2_DATA:-$root/.zero/llama2-data}"
zero="$root/bin/zero"
img="alpine"
plat="linux/amd64"

model_url="https://huggingface.co/karpathy/tinyllamas/resolve/main/stories15M.bin"
tok_url="https://github.com/karpathy/llama2.c/raw/master/tokenizer.bin"
runc_url="https://github.com/karpathy/llama2.c/raw/master/run.c"
runqc_url="https://github.com/karpathy/llama2.c/raw/master/runq.c"

# Quantized ("version 2", runq.c) checkpoint. Unlike stories15M.bin it is not a
# plain download: it is produced by a one-time `export.py --version 2` step that
# needs PyTorch + the stories15M.pt weights (see below). When it is absent the
# quantized parity matrix self-skips so the dependency-free f32 matrix still runs.
model_q="stories15M_q80.bin"

command -v docker >/dev/null 2>&1 || { echo "error: docker is required (runs the linux-musl-x64 binaries under amd64)." >&2; exit 1; }
command -v zig >/dev/null 2>&1 || { echo "error: zig is required (builds the C reference against the same bundled musl libm the Zero exe links)." >&2; exit 1; }
[ -x "$zero" ] || { echo "error: $zero not built. Run: make -C native/zero-c" >&2; exit 1; }

# Build a C reference (run.c / runq.c) with the SAME toolchain the Zero exe links
# — zig cc cross-compiling to the linux-musl-x64 triple — so both sides share one
# musl libm. Building it with the container's Alpine gcc/musl instead skews libm
# (its expf etc. differ by ~1 ULP) and breaks token-for-token parity. The output
# is a static linux-musl-x64 ELF, run later in the amd64 container alongside the
# Zero exe. Reuses Zero's own zig cache dirs.
musl_triple="x86_64-linux-musl"
build_ref() { # build_ref <src.c> <out-binary> [extra cc flags...]
  src="$1"; out="$2"; shift 2
  ZIG_GLOBAL_CACHE_DIR="$root/.zero/zig-global-cache" \
  ZIG_LOCAL_CACHE_DIR="$root/.zero/zig-local-cache" \
    zig cc -target "$musl_triple" -O3 "$@" -o "$data/$out" "$data/$src"
}

mkdir -p "$data"
echo "==> fetching weights + reference into $data"
[ -f "$data/stories15M.bin" ] || curl -fSL -o "$data/stories15M.bin" "$model_url"
[ -f "$data/tokenizer.bin" ]  || curl -fSL -o "$data/tokenizer.bin"  "$tok_url"
[ -f "$data/run.c" ]          || curl -fSL -o "$data/run.c"          "$runc_url"

echo "==> building llama2.zero (--backend zero-elf64, linux-musl-x64)"
"$zero" build --backend zero-elf64 --emit exe --target linux-musl-x64 "$root/examples/llama2" --out "$data/llama2" >/dev/null
echo "==> building llama2.c reference (zig cc + bundled musl, matching the Zero exe)"
# run.c relies on transitive stdint.h (glibc); musl needs it forced.
build_ref run.c run_ref -include stdint.h

# Both sides now expand raw-byte <0xNN> tokens to the actual byte, so the streams
# are directly byte-comparable.
norm_and_diff() {
  if cmp -s "$1" "$2"; then
    return 0
  fi
  echo "--- llama2.zero" >&2
  cat "$1" >&2
  echo "--- llama2.c" >&2
  cat "$2" >&2
  return 1
}

# parity_one <temperature> <tokens> <prompt>
parity_one() {
  t="$1"; n="$2"; p="$3"
  if [ "$t" = "0" ]; then ref_extra=""; else ref_extra="-p 0 -s 12345"; fi
  docker run --rm --platform "$plat" -v "$data":/work -w /work "$img" sh -c "
    ./llama2 stories15M.bin --prompt '$p' --tokens $n --temperature $t 2>/dev/null > z.txt
    ./run_ref stories15M.bin -z tokenizer.bin -t $t $ref_extra -n $n -i '$p' 2>/dev/null > r.txt
  "
  if norm_and_diff "$data/z.txt" "$data/r.txt"; then
    echo "  OK   [t=$t, $n tok] \"$p\""
  else
    echo "  FAIL [t=$t, $n tok] \"$p\""
    return 1
  fi
}

# parity_topp <temperature> <tokens> <topp> <prompt> — top-p (nucleus) path. The
# reference gets a real `-p <topp>` (not `-p 0`) plus the matched seed; the Zero
# side gets `--topp <topp>`. Same xorshift* PRNG + same sample_topp => identical
# streams.
parity_topp() {
  t="$1"; n="$2"; pp="$3"; p="$4"
  docker run --rm --platform "$plat" -v "$data":/work -w /work "$img" sh -c "
    ./llama2 stories15M.bin --prompt '$p' --tokens $n --temperature $t --topp $pp 2>/dev/null > z.txt
    ./run_ref stories15M.bin -z tokenizer.bin -t $t -p $pp -s 12345 -n $n -i '$p' 2>/dev/null > r.txt
  "
  if norm_and_diff "$data/z.txt" "$data/r.txt"; then
    echo "  OK   [t=$t, p=$pp, $n tok] \"$p\""
  else
    echo "  FAIL [t=$t, p=$pp, $n tok] \"$p\""
    return 1
  fi
}

# parity_one_q / parity_topp_q — the quantized (runq.c "version 2") analogues of
# parity_one / parity_topp. Identical machinery, but the Zero exe is pointed at
# the quantized checkpoint (it auto-detects the v2 magic — no flag) and the C
# reference is `runq_ref` (built from runq.c). runq.c takes the exact same CLI
# flags as run.c, so the seed (12345), prompt set and normalization carry over.
parity_one_q() {
  t="$1"; n="$2"; p="$3"
  if [ "$t" = "0" ]; then ref_extra=""; else ref_extra="-p 0 -s 12345"; fi
  docker run --rm --platform "$plat" -v "$data":/work -w /work "$img" sh -c "
    ./llama2 $model_q --prompt '$p' --tokens $n --temperature $t 2>/dev/null > zq.txt
    ./runq_ref $model_q -z tokenizer.bin -t $t $ref_extra -n $n -i '$p' 2>/dev/null > rq.txt
  "
  if norm_and_diff "$data/zq.txt" "$data/rq.txt"; then
    echo "  OK   [q, t=$t, $n tok] \"$p\""
  else
    echo "  FAIL [q, t=$t, $n tok] \"$p\""
    return 1
  fi
}

parity_topp_q() {
  t="$1"; n="$2"; pp="$3"; p="$4"
  docker run --rm --platform "$plat" -v "$data":/work -w /work "$img" sh -c "
    ./llama2 $model_q --prompt '$p' --tokens $n --temperature $t --topp $pp 2>/dev/null > zq.txt
    ./runq_ref $model_q -z tokenizer.bin -t $t -p $pp -s 12345 -n $n -i '$p' 2>/dev/null > rq.txt
  "
  if norm_and_diff "$data/zq.txt" "$data/rq.txt"; then
    echo "  OK   [q, t=$t, p=$pp, $n tok] \"$p\""
  else
    echo "  FAIL [q, t=$t, p=$pp, $n tok] \"$p\""
    return 1
  fi
}

fail=0
echo "==> temperature 0 (deterministic argmax) parity"
parity_one 0 100 "Once upon a time" || fail=1
parity_one 0 120 "Lily and Tom went to the park" || fail=1
parity_one 0 80  "The little robot" || fail=1
parity_one 0 256 "One day" || fail=1
parity_one 0 60  "" || fail=1

echo "==> temperature > 0 (softmax + xorshift* PRNG + multinomial) parity"
parity_one 0.8 100 "Once upon a time" || fail=1
parity_one 1.0 100 "The dragon" || fail=1
parity_one 0.5 80  "" || fail=1

echo "==> temperature > 0 with top-p (nucleus) parity"
parity_topp 0.8 100 0.9  "Once upon a time" || fail=1
parity_topp 1.0 100 0.95 "The dragon" || fail=1
parity_topp 0.9 80  0.9  "" || fail=1

# Quantized (int8, runq.c "version 2") parity. Same engine, no flag — the v2
# magic is auto-detected. The quantized checkpoint is a one-time export, so this
# matrix self-skips (never failing the run) when $model_q is absent, keeping the
# f32 matrix above dependency-free. To enable it, produce the checkpoint once:
#   pip install torch numpy
#   curl -fSL -o stories15M.pt \
#     https://huggingface.co/karpathy/tinyllamas/resolve/main/stories15M.pt
#   curl -fSL -o export.py https://github.com/karpathy/llama2.c/raw/master/export.py
#   python export.py "$LLAMA2_DATA/stories15M_q80.bin" --version 2 --checkpoint stories15M.pt
quant_ran=0
if [ -f "$data/$model_q" ]; then
  echo "==> fetching + building runq.c reference (int8; zig cc + bundled musl)"
  [ -f "$data/runq.c" ] || curl -fSL -o "$data/runq.c" "$runqc_url"
  # runq.c already #includes <stdint.h> (run.c does not), so no -include is needed.
  build_ref runq.c runq_ref

  echo "==> [quantized] temperature 0 (deterministic argmax) parity"
  parity_one_q 0 100 "Once upon a time" || fail=1
  parity_one_q 0 120 "Lily and Tom went to the park" || fail=1
  parity_one_q 0 80  "The little robot" || fail=1
  parity_one_q 0 60  "" || fail=1

  echo "==> [quantized] temperature > 0 (multinomial) parity"
  parity_one_q 0.8 100 "Once upon a time" || fail=1
  parity_one_q 1.0 100 "The dragon" || fail=1

  echo "==> [quantized] temperature > 0 with top-p (nucleus) parity"
  parity_topp_q 0.8 100 0.9  "Once upon a time" || fail=1
  parity_topp_q 0.9 80  0.9  "" || fail=1
  quant_ran=1
else
  echo "==> [quantized] SKIP: $model_q not found in $data."
  echo "    The int8 parity matrix needs a one-time 'python export.py $model_q"
  echo "    --version 2 --checkpoint stories15M.pt' step (requires PyTorch +"
  echo "    stories15M.pt); see the comment above this block. The f32 matrix"
  echo "    above is unaffected. This is a skip, not a failure."
fi

# Informational throughput note (sorted-index tokenizer lookup).
# The tokenizer is no longer an O(vocab) linear scan, but end-to-end tok/s is
# dominated by the forward pass — this is a coarse wall-clock figure under amd64
# qemu, not an isolated tokenizer benchmark. Not gated (never sets fail).
echo "==> throughput (informational, end-to-end under qemu)"
bench_n=256
t_start=$(date +%s)
docker run --rm --platform "$plat" -v "$data":/work -w /work "$img" sh -c \
  "./llama2 stories15M.bin --prompt 'Once upon a time' --tokens $bench_n --temperature 0 >/dev/null 2>&1" || true
t_end=$(date +%s)
elapsed=$(( t_end - t_start ))
if [ "$elapsed" -gt 0 ]; then
  echo "  $bench_n tokens in ${elapsed}s (~$(( bench_n / elapsed )) tok/s, incl. model load)"
else
  echo "  $bench_n tokens in <1s"
fi

if [ "$fail" -eq 0 ]; then
  echo "==> PASS: llama2.zero matches llama2.c token-for-token on stories15M (f32)."
  if [ "$quant_ran" -eq 1 ]; then
    echo "==> PASS: llama2.zero matches runq.c token-for-token on $model_q (int8)."
  else
    echo "==> NOTE: int8 (runq.c) parity skipped — $model_q absent (see SKIP note above)."
  fi
else
  echo "==> FAIL: divergence found (see diffs above)." >&2
  exit 1
fi
